language: generic
sudo: required
services:
  - docker
env:
  global:
    - DOCKERBUILDER=greenaddress/core_builder_for_android
    - DOCKERHASH=40d2bd11a57d65dee105567a8c815b554116f67c2c89de9ec146b098a0c4c64d
    - REPO=https://github.com/projectcoincore/ProjectCoin.git
    - COMMIT=63fbb6cfa2d3ac90b6cd1bfe37b8d7b4b163c0ec
    - TOOLCHAIN=aarch64-linux-android-clang
    - TARGETHOST=aarch64-linux-android
    - BITS=64
  matrix:
    - UNUSED=true
    - TOOLCHAIN=arm-linux-androideabi-clang TARGETHOST=arm-linux-androideabi BITS=32
    - TOOLCHAIN=x86_64-clang TARGETHOST=x86_64-linux-android
    - TOOLCHAIN=x86-clang TARGETHOST=i686-linux-android BITS=32

script:
  - docker run -v $PWD:/repo $DOCKERBUILDER@sha256:$DOCKERHASH /bin/bash -c "/repo/fetchbuild.sh $REPO $COMMIT $TOOLCHAIN $TARGETHOST $BITS"
